const IS_PRODUCTION = import.meta.env.PROD;
const AUTH_REDIRECT_URI = import.meta.env.VITE_AUTH0_REDIRECT_URI;

const enviroment = {
  CLIENT_ID: import.meta.env.VITE_AUTH0_CLIENT_ID,
  CLIENT_SECRET: import.meta.env.VITE_AUTH0_CLIENT_SECRET,
  REALM: import.meta.env.VITE_AUTH_REALM,
  PROVIDER: import.meta.env.VITE_AUTH_PROVIDER,
  REDIRECT_URI: IS_PRODUCTION ? window.location.origin : AUTH_REDIRECT_URI,
  ICLIENT_API_URL_QUERY: import.meta.env.VITE_ICLIENT_API_URL_QUERY,
  ICLIENT_API_URL_QUERY_PROCESS: import.meta.env
    .VITE_IUTILITIES_LINIX_CATALOGOS_GENERALES_API_URL_QUERY_PROCESS,
  IVITE_ISAAS_QUERY_PROCESS_SERVICE: import.meta.env
    .VITE_ISAAS_QUERY_PROCESS_SERVICE,
  IVITE_IPORTAL_STAFF_QUERY_PROCESS_SERVICE: import.meta.env
    .VITE_IPORTAL_STAFF_QUERY_PROCESS_SERVICE,
  ICLIENT_API_URL_PERSISTENCE_POST: import.meta.env
    .VITE_IUTILITIES_LINIX_CATALOGOS_GENERALES_API_URL_PERSISTENCE_PROCESS,
  TEMP_BUSINESS_UNIT: "LINIX",
  ICLIENT_API_URL_QUERY_USERS_PROCESS: import.meta.env
    .VITE_IPRIVILEGES_LINIX_API_URL_QUERY_DATA_SERVICE,
  AUTH0_DOMAIN: import.meta.env.VITE_AUTH0_DOMAIN,
  MAX_RETRIES_SERVICES: Number(import.meta.env.VITE_MAX_RETRIES_SERVICES),
  FETCH_TIMEOUT_SERVICES: Number(import.meta.env.VITE_FETCH_TIMEOUT_SERVICES),
  MEDIA_QUERY_MOBILE: import.meta.env.VITE_MEDIA_QUERY_MOBILE,
  SECRET_KEY_PORTAL_ID: import.meta.env.VITE_SECRET_KEY_PORTAL_ID,
  SECRET_KEY_PORTAL_NAME: import.meta.env.VITE_SECRET_KEY_PORTAL_NAME,
  IS_MOBILE_580: import.meta.env.VITE_IS_MOBILE_580,
  IS_MOBILE_743: import.meta.env.VITE_IS_MOBILE_743,
  IS_MOBILE_849: import.meta.env.VITE_IS_MOBILE_849,
  IS_MOBILE_970: import.meta.env.VITE_IS_MOBILE_970,
};

export { enviroment };
